openapi: 3.0.3
info:
  title: TestFire Login API
  version: 1.0.0

servers:
  - url: https://demo.testfire.net/api

paths:
  /login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: OK
