env:
  context:
    name: "ctx"
    urls:
      - "https://demo.testfire.net"

jobs:
  - type: requestor
    name: login-post
    requests:
      - url: "https://demo.testfire.net/login"
        method: "POST"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        data: "uid=admin&pass=admin"

  - type: activeScan
    name: active-scan
    context: "ctx"
    parameters:
      policy: "API-scan"

  - type: report
    name: html-report
    parameters:
      format: "HTML"
      outfile: "/zap/wrk/zap-report.html"
