env:
  contexts:
    - name: testfire
      urls:
        - "https://demo.testfire.net"

jobs:
  - type: requestor
    name: "Single POST Login"
    data:
      requests:
        - url: "https://demo.testfire.net/api/login"
          method: "POST"
          headers:
            Content-Type: "application/json"
          body: |
            {
              "username": "jsmith",
              "password": "demo1234"
            }
