openapi: 3.0.3
info:
  title: TestFire Single POST API
  version: 1.0.0

servers:
  - url: https://demo.testfire.net

paths:
  /login:
    post:
      summary: User login
      description: Login method extracted from TestFire API.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Login successful
        "400":
          description: Invalid parameters
        "500":
          description: Server error
