---
version: "1.0"

env:
  parameters: {}

jobs:
  - type: requestor
    name: login-post
    parameters:
      requests:
        - url: "https://demo.testfire.net/login"
          method: "POST"
          body: "uid=admin&pass=admin"
          headers:
            Content-Type: "application/x-www-form-urlencoded"

  - type: passiveScan-wait
    name: wait-passive
    parameters:
      maxDuration: 60

  - type: report
    name: report
    parameters:
      reportDir: "zap-report"
      reportFile: "post-login.html"
      template: "traditional-html"
