openapi: 3.0.3
info:
  title: TestFire Login Form API
  version: 1.0.0

servers:
  - url: https://demo.testfire.net

paths:
  /doLogin:
    post:
      summary: Login form POST
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                uid:
                  type: string
                passw:
                  type: string
              required:
                - uid
                - passw
      responses:
        "302":
          description: Redirect after login
        "200":
          description: Login failed
